### ISSUE TITLE
关于数据源的配置问题

### ISSUE THREAD

**Issue by qinjc** [MorvanZhou/celebA-cyclegan#1]
从dataset.py来看我需要在如下目录新建一个txt
D:\data\celebA_img_align\list_attr_celeba.txt
请问该txt内需要配置哪些信息？有没有其他需要额外配置的？

**Comment by MorvanZhou** [comment]
我在README.md 现已中加入数据源信息. https://github.com/MorvanZhou/celebA-cyclegan
